# Generated by Django 5.0.3 on 2024-03-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_clubs', '0003_remove_review_stars_remove_review_unfinished_and_more'),
    ]

    operations = [
    ]
