# Generated by Django 5.0.3 on 2024-03-17 22:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_clubs', '0004_auto_20240316_1740'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='club',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='club',
            name='owner',
        ),
        migrations.AddField(
            model_name='club',
            name='Postal_Code',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='unique_identifier',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='activity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rating',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='hobby_clubs.club'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
