# Generated by Django 5.0.3 on 2024-03-18 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_clubs', '0005_remove_club_date_added_remove_club_date_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='Postal_Code',
            new_name='postal_code',
        ),
    ]
